[package]
name = "integration_tests"
version = "0.0.1"
authors = [ "The Servo Project Developers" ]
build = "build.rs"
publish = false
edition = "2024"

[lib]
doctest = false
test = true

[[bench]]
name = "micro"
harness = false

[dependencies]
string_cache = { path = ".." }

[dev-dependencies]
criterion = { version = "0.8.2", features = ["html_reports"] }
rand = { version = "0.8", features = ["small_rng"] }
string_cache_codegen = { path = "../string-cache-codegen" }

[build-dependencies]
string_cache_codegen = { path = "../string-cache-codegen" }
